server:
    port: 8082
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: Gisquest.2021
        url: jdbc:postgresql://192.168.11.73:5432/gisqdb_lujq?currentSchema=mall&serverTimezone=GMT%2B8&useSSL=false
    redis:
        host: localhost
        port: 6379
        database: 0
        password: redis@gisquest.com
rocketmq:
    name-server: 192.168.16.152:9876
#    consumer:
#        access-key: rocketmq2
#        secret-key: 12345678
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl